zebra: reuse old nhe when only recursive nexthops changed
When a failover happens on ECMP paths that use the same
nexthop which is recursively resolved, ZEBRA replaces the
old NHG with a new one, and updates the pointer of all
routes using that nexthop.

Actually, if only the recursive nexthop changed, there is
no need to replace the old NHG.
Modify the zebra_nhg_proto_add() function, by updating
the recursive nexthop on the original NHG.

Using this change replaces the old method that was consisting in
allocating a new nhe. This change triggers an ASAN in the
bgp_nhg_zapi_scalability test, function
test_bgp_ipv4_simulate_r5_machine_going_down().

> r1: zebra triggered an exception by AddressSanitizer
> AddressSanitizer error in topotest `test_bgp_nhg_zapi_scalability.py`, test `teardown_module`, router `r1`
>
> ERROR: AddressSanitizer: heap-use-after-free on address 0x60e00230afa0 at pc 0x55bfebc9681e bp 0x7ffd657ceb40 sp 0x7ffd657ceb30
> READ of size 4 at 0x60e00230afa0 thread T0
>     #0 0x55bfebc9681d in zebra_nhg_decrement_ref zebra/zebra_nhg.c:1855
>     #1 0x55bfebc967f7 in zebra_nhg_decrement_ref zebra/zebra_nhg.c:1868
>     #2 0x55bfebcb32f6 in route_entry_update_nhe zebra/zebra_rib.c:460
>     #3 0x55bfebcb352f in rib_handle_nhg_replace zebra/zebra_rib.c:486
>     #4 0x55bfebc99c14 in zebra_nhg_proto_add zebra/zebra_nhg.c:3836
>     #5 0x55bfebcc4035 in process_subq_nhg zebra/zebra_rib.c:2763
>     #6 0x55bfebcc4035 in process_subq zebra/zebra_rib.c:3369
>     #7 0x55bfebcc4035 in meta_queue_process zebra/zebra_rib.c:3422
>     #8 0x7f458a518bff in work_queue_run lib/workqueue.c:282
>     #9 0x7f458a4fa24b in event_call lib/event.c:2019
>     #10 0x7f458a41f717 in frr_run lib/libfrr.c:1238
>     #11 0x55bfebb82cb4 in main zebra/main.c:528
>     #12 0x7f4589e29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
>     #13 0x7f4589e29e3f in __libc_start_main_impl ../csu/libc-start.c:392
>     #14 0x55bfebb85c34 in _start (/usr/lib/frr/zebra+0x1abc34)
>
> 0x60e00230afa0 is located 96 bytes inside of 160-byte region [0x60e00230af40,0x60e00230afe0)
> freed by thread T0 here:
>     #0 0x7f458a8b4537 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127
>     #1 0x55bfebc967f7 in zebra_nhg_decrement_ref zebra/zebra_nhg.c:1868
>     #2 0x55bfebcb32f6 in route_entry_update_nhe zebra/zebra_rib.c:460
>     #3 0x55bfebcb352f in rib_handle_nhg_replace zebra/zebra_rib.c:486
>     #4 0x55bfebc99c14 in zebra_nhg_proto_add zebra/zebra_nhg.c:3836
>     #5 0x55bfebcc4035 in process_subq_nhg zebra/zebra_rib.c:2763
>     #6 0x55bfebcc4035 in process_subq zebra/zebra_rib.c:3369
>     #7 0x55bfebcc4035 in meta_queue_process zebra/zebra_rib.c:3422
>     #8 0x7f458a518bff in work_queue_run lib/workqueue.c:282
>     #9 0x7f458a4fa24b in event_call lib/event.c:2019
>     #10 0x7f458a41f717 in frr_run lib/libfrr.c:1238
>     #11 0x55bfebb82cb4 in main zebra/main.c:528
>     #12 0x7f4589e29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
>
> previously allocated by thread T0 here:
>     #0 0x7f458a8b4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
>     #1 0x7f458a43fb7e in qcalloc lib/memory.c:106
>     #2 0x55bfebc91f2e in zebra_nhg_alloc zebra/zebra_nhg.c:392
>     #3 0x55bfebc91f2e in zebra_nhe_copy zebra/zebra_nhg.c:499
>     #4 0x55bfebc922af in zebra_nhg_hash_alloc zebra/zebra_nhg.c:538
>     #5 0x7f458a3fd0bd in hash_get lib/hash.c:147
>     #6 0x55bfebc94d7a in zebra_nhe_find zebra/zebra_nhg.c:831
>     #7 0x55bfebc953ef in zebra_nhg_find zebra/zebra_nhg.c:1013
>     #8 0x55bfebc9585d in zebra_nhg_find_nexthop zebra/zebra_nhg.c:1030
>     #9 0x55bfebc94078 in depends_find_recursive zebra/zebra_nhg.c:1511
>     #10 0x55bfebc94078 in depends_find zebra/zebra_nhg.c:1560
>     #11 0x55bfebc94078 in depends_find_add zebra/zebra_nhg.c:1599
>     #12 0x55bfebc99e40 in zebra_nhg_update_nhe zebra/zebra_nhg.c:3732
>     #13 0x55bfebc99e40 in zebra_nhg_proto_add zebra/zebra_nhg.c:3819
>     #14 0x55bfebcc4035 in process_subq_nhg zebra/zebra_rib.c:2763
>     #15 0x55bfebcc4035 in process_subq zebra/zebra_rib.c:3369
>     #16 0x55bfebcc4035 in meta_queue_process zebra/zebra_rib.c:3422
>     #17 0x7f458a518bff in work_queue_run lib/workqueue.c:282
>     #18 0x7f458a4fa24b in event_call lib/event.c:2019
>     #19 0x7f458a41f717 in frr_run lib/libfrr.c:1238
>     #20 0x55bfebb82cb4 in main zebra/main.c:528
>     #21 0x7f4589e29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
>
> SUMMARY: AddressSanitizer: heap-use-after-free zebra/zebra_nhg.c:1855 in zebra_nhg_decrement_ref
> Shadow bytes around the buggy address:
>   0x0c1c804595a0: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
>   0x0c1c804595b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c1c804595c0: fd fd fd fa fa fa fa fa fa fa fa fa fd fd fd fd
>   0x0c1c804595d0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
>   0x0c1c804595e0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
> =>0x0c1c804595f0: fd fd fd fd[fd]fd fd fd fd fd fd fd fa fa fa fa
>   0x0c1c80459600: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c1c80459610: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
>   0x0c1c80459620: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c1c80459630: fd fd fd fa fa fa fa fa fa fa fa fa 00 00 00 00
>   0x0c1c80459640: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07
>   Heap left redzone:       fa
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
>   Left alloca redzone:     ca
>   Right alloca redzone:    cb
>   Shadow gap:              cc
>

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>