bgpd: Fix heap-use-after-free in bgp_evpn_mh_finish
In bgp_evpn_mh_finish(), accessing es->es_evi_list after calling
bgp_evpn_es_local_info_clear() causes use-after-free when the ES
gets freed.

Fix by checking and cleaning ES-EVIs before clearing local info.

AddressSanitizer error in topotest `test_bgp_evpn_ead_evi_routes.py`, test `check_daemon`, router `tor2`

ERROR: AddressSanitizer: heap-use-after-free on address 0xffff817d9f28 at pc 0xaaaae8a31974 bp 0xffffc069e410 sp 0xffffc069e400
READ of size 8 at 0xffff817d9f28 thread T0
    #0 0xaaaae8a31970 in bgp_evpn_mh_finish bgpd/bgp_evpn_mh.c:5093
    #1 0xaaaae89b66bc in bgp_exit bgpd/bgp_main.c:193
    #2 0xaaaae89b66bc in sigint bgpd/bgp_main.c:141
    #3 0xffff862f6440 in frr_sigevent_process lib/sigevent.c:117
    #4 0xffff8632095c in event_fetch_inner_loop lib/event.c:2427
    #5 0xffff8632095c in event_fetch lib/event.c:2559
    #6 0xffff86258100 in frr_run lib/libfrr.c:1257
    #7 0xaaaae89af55c in main bgpd/bgp_main.c:549
    #8 0xffff85c773fc in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #9 0xffff85c774d4 in __libc_start_main_impl ../csu/libc-start.c:392
    #10 0xaaaae89b4dac in _start (/usr/lib/frr/bgpd+0x2e4dac)

0xffff817d9f28 is located 168 bytes inside of 248-byte region [0xffff817d9e80,0xffff817d9f78)
freed by thread T0 here:
    #0 0xffff8669f0d8 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127
    #1 0xaaaae8a316f0 in bgp_evpn_es_local_info_clear bgpd/bgp_evpn_mh.c:2058
    #2 0xaaaae8a316f0 in bgp_evpn_mh_finish bgpd/bgp_evpn_mh.c:5088
    #3 0xaaaae89b66bc in bgp_exit bgpd/bgp_main.c:193
    #4 0xaaaae89b66bc in sigint bgpd/bgp_main.c:141
    #5 0xffff862f6440 in frr_sigevent_process lib/sigevent.c:117
    #6 0xffff8632095c in event_fetch_inner_loop lib/event.c:2427
    #7 0xffff8632095c in event_fetch lib/event.c:2559
    #8 0xffff86258100 in frr_run lib/libfrr.c:1257
    #9 0xaaaae89af55c in main bgpd/bgp_main.c:549
    #10 0xffff85c773fc in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #11 0xffff85c774d4 in __libc_start_main_impl ../csu/libc-start.c:392
    #12 0xaaaae89b4dac in _start (/usr/lib/frr/bgpd+0x2e4dac)

previously allocated by thread T0 here:
    #0 0xffff8669f5f4 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0xffff86277c30 in qcalloc lib/memory.c:111
    #2 0xaaaae8a19ba8 in bgp_evpn_es_new bgpd/bgp_evpn_mh.c:1925
    #3 0xaaaae8a2a4d4 in bgp_evpn_local_es_add bgpd/bgp_evpn_mh.c:2420
    #4 0xaaaae8bc7080 in bgp_zebra_process_local_es_add bgpd/bgp_zebra.c:3272
    #5 0xffff863511c4 in zclient_read lib/zclient.c:4870
    #6 0xffff863212e4 in event_call lib/event.c:2730
    #7 0xffff862580f4 in frr_run lib/libfrr.c:1258
    #8 0xaaaae89af55c in main bgpd/bgp_main.c:549
    #9 0xffff85c773fc in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #10 0xffff85c774d4 in __libc_start_main_impl ../csu/libc-start.c:392
    #11 0xaaaae89b4dac in _start (/usr/lib/frr/bgpd+0x2e4dac)

SUMMARY: AddressSanitizer: heap-use-after-free bgpd/bgp_evpn_mh.c:5093 in bgp_evpn_mh_finish

Signed-off-by: Rajasekar Raja <rajasekarr@nvidia.com>
(cherry picked from commit c7971628430d77e09b519b9f03d912682e11f3d7)

PR: 101860
Signed-off-by: Loïc Sang <loic.sang@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>