lib: fix compilation without have_mgmtd definition
> In file included from lib/if_rmap.c:16:
> ./lib/if_rmap_clippy.c:1:5: error: "HAVE_MGMTD" is not defined, evaluates to 0 [-Werror=undef]
>     1 | #if HAVE_MGMTD
>       |     ^~~~~~~~~~
> ./lib/if_rmap_clippy.c:65:5: error: "HAVE_MGMTD" is not defined, evaluates to 0 [-Werror=undef]
>    65 | #if HAVE_MGMTD
>       |     ^~~~~~~~~~
> ./lib/if_rmap_clippy.c:125:5: error: "HAVE_MGMTD" is not defined, evaluates to 0 [-Werror=undef]
>   125 | #if HAVE_MGMTD
>       |     ^~~~~~~~~~
> ./lib/if_rmap_clippy.c:189:5: error: "HAVE_MGMTD" is not defined, evaluates to 0 [-Werror=undef]
>   189 | #if HAVE_MGMTD
>       |     ^~~~~~~~~~
> lib/if_rmap.c:188:5: error: "HAVE_MGMTD" is not defined, evaluates to 0 [-Werror=undef]
>   188 | #if HAVE_MGMTD
>       |     ^~~~~~~~~~
> lib/if_rmap.c:307:5: error: "HAVE_MGMTD" is not defined, evaluates to 0 [-Werror=undef]
>   307 | #if HAVE_MGMTD
>       |     ^~~~~~~~~~

PR: 95710
Fixes: 78c05b505e ("if_rmap: move rmap config to daemon")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Loïc Sang <loic.sang@6wind.com>