pimd: Prevent use after free when removing a pim_upstream
CI is seeing this upon freeing an upstream variable:

    ERROR: AddressSanitizer: heap-use-after-free on address 0x61300009617c at pc 0x557b9d225cac bp 0x7ffde36f7a90 sp 0x7ffde36f7a88
    READ of size 4 at 0x61300009617c thread T0
        0 0x557b9d225cab in pim_jp_groups_source_set_prune pimd/pim_join.c:573
        1 0x557b9d225cab in pim_jp_send pimd/pim_join.c:975
        2 0x557b9d2296b3 in pim_joinprune_send pimd/pim_join.c:1085
        3 0x557b9d29655c in pim_zebra_update_all_interfaces pimd/pim_zebra.c:233
        4 0x557b9d24ebb5 in pim_update_upstream_nh pimd/pim_nht.c:1033
        5 0x557b9d25adb6 in pim_nexthop_update pimd/pim_nht.c:1957
        6 0x7f895432b84e in zclient_nexthop_update lib/zclient.c:4758
        7 0x7f89543251b0 in zclient_read lib/zclient.c:4888
        8 0x7f89542f4893 in event_call lib/event.c:2744
        9 0x7f8954210544 in frr_run lib/libfrr.c:1258
        10 0x557b9d3111a0 in main pimd/pim_main.c:169
        11 0x7f8953c1b249 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
        12 0x7f8953c1b304 in __libc_start_main_impl ../csu/libc-start.c:360
        13 0x557b9d1de7f0 in _start (/usr/lib/frr/pimd+0x1487f0)

    0x61300009617c is located 60 bytes inside of 352-byte region [0x613000096140,0x6130000962a0)
    freed by thread T0 here:
        0 0x7f89546b76a8 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52
        1 0x7f8954235bcb in qfree lib/memory.c:136
        2 0x557b9d285ff3 in pim_upstream_del pimd/pim_upstream.c:287
        3 0x557b9d285ca9 in pim_upstream_remove_children pimd/pim_upstream.c:71
        4 0x557b9d285ca9 in pim_upstream_del pimd/pim_upstream.c:256
        5 0x557b9d21d281 in pim_ifchannel_delete pimd/pim_ifchannel.c:190
        6 0x557b9d208592 in clear_mroute pimd/pim_cmd_common.c:4481
        7 0x557b9d2b630f in clear_ip_mroute_magic pimd/pim_cmd.c:1537
        8 0x557b9d2b630f in clear_ip_mroute pimd/pim_cmd_clippy.c:86
        9 0x7f89541a4d8e in cmd_execute_command_real lib/command.c:1014
        10 0x7f89541a50ad in cmd_execute_command lib/command.c:1073
        11 0x7f89541a55d9 in cmd_execute lib/command.c:1239
        12 0x7f8954301b2c in vty_command lib/vty.c:593
        13 0x7f8954302079 in vty_execute lib/vty.c:1356
        14 0x7f89543090a7 in vtysh_read lib/vty.c:2302
        15 0x7f89542f4893 in event_call lib/event.c:2744
        16 0x7f8954210544 in frr_run lib/libfrr.c:1258
        17 0x557b9d3111a0 in main pimd/pim_main.c:169
        18 0x7f8953c1b249 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

    previously allocated by thread T0 here:
        0 0x7f89546b83b7 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:77
        1 0x7f89542352d8 in qcalloc lib/memory.c:111
        2 0x557b9d28d1d0 in pim_upstream_new pimd/pim_upstream.c:1198
        3 0x557b9d28d1d0 in pim_upstream_add pimd/pim_upstream.c:1417
        4 0x557b9d22f9da in pim_mroute_msg_wholepkt pimd/pim_mroute.c:632
        5 0x557b9d239243 in pim_mroute_msg pimd/pim_mroute.c:1448
        6 0x557b9d23956c in mroute_read pimd/pim_mroute.c:1490
        7 0x7f89542f4893 in event_call lib/event.c:2744
        8 0x7f8954210544 in frr_run lib/libfrr.c:1258
        9 0x557b9d3111a0 in main pimd/pim_main.c:169
        10 0x7f8953c1b249 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Effectively when the pim_upstream is deleted it is leaving the upstream in the jp group send
hung off the interface.  Add a bit of code on final deletion that prevents this from happening.

Signed-off-by: Donald Sharp <sharpd@nvidia.com>
(cherry picked from commit 417bd111a7c8c8896e1eabad92951b83f66d486b)