tests: fix label chunk available notification
Fix test compilation:

>   CCLD     tests/zebra/test_lm_plugin
> /usr/bin/ld: zebra/label_manager.o: warning: relocation against `zrouter' in read-only section `.text'
> /usr/bin/ld: zebra/label_manager.o: in function `label_manager_label_chunk_free_notify':
> /home/lscalber/git/frr/zebra/label_manager.c:563: undefined reference to `zebra_mpls_static_label_chunk_free_notify'
> /usr/bin/ld: /home/lscalber/git/frr/zebra/label_manager.c:565: undefined reference to `zrouter'
> /usr/bin/ld: /home/lscalber/git/frr/zebra/label_manager.c:565: undefined reference to `zrouter'
> /usr/bin/ld: /home/lscalber/git/frr/zebra/label_manager.c:575: undefined reference to `zserv_send_message'
> /usr/bin/ld: warning: creating DT_TEXTREL in a PIE
> collect2: error: ld returned 1 exit status
> make[1]: *** [Makefile:8945: tests/zebra/test_lm_plugin] Error 1

PR: 87864
Fixes: f52f0fc195 ("lib, zebra: send notification to clients when a label chunk available")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>
(cherry picked from commit 7db1de3d0c1a1111fec3036375ce7a5d2b66cb3a)

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>