bgpd: fix uninitialized flag in l2vpn
From buildtest:
../sdist/bgpd/bgp_l2vpn.c:314:7: error: variable 'flag' is used
uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]

This variable is used in multihoming case, as now it is unsupported,
let's remove first.

Fixes: d5d16f664ae1 ("bgpd: support evpn vxlan vpws")
PR: 103070
Signed-off-by: Loïc Sang <loic.sang@6wind.com>
Acked-by: Louis Scalbert <louis.scalbert@6wind.com>