bgp: fix printing flowspec match bitmask
Flowspec match bitmask is printed on console with a non ASCII character.
This is not portable and causes issue when parsing output with python3
topotests.

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 23478: ordinal not in range(128)

> $ git grep $'â' bgpd/
> bgpd/bgp_flowspec_util.c:                                                      "<E2><88><8B> ");

The special character has actually the UTF-8 code 0xe2888b.

Print "match" instead.

PR: 88387
Link: https://datatracker.ietf.org/doc/html/rfc8955#section-4.2.1.2
Fixes: 01ffd28b8d ("bgpd: fix display with flowspec tcp flags option")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>

(cherry picked from commit cbe590a75fcd7ad09a2cabbfe53a1f5844b831cf)

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>