topotato: update documentation
TimedElement is not in .base anymore.  Also pytest docstrings leak in
for TopotatoItem, causing an undefined reference to "non-python tests".

Signed-off-by: David Lamparter <equinox@diac24.net>