tests: fix notify static lsp when label chunk available
Fix compilation error:

>   CCLD     tests/zebra/test_lm_plugin
> /usr/bin/ld: zebra/label_manager.o: in function `label_manager_label_chunk_free_notify':
> /home/lscalber/git/frr/zebra/label_manager.c:563: undefined reference to `zebra_mpls_static_label_chunk_free_notify'
> collect2: error: ld returned 1 exit status
> make[1]: *** [Makefile:8945: tests/zebra/test_lm_plugin] Error 1

PR: 87864
Fixes: 633df309f0 ("zebra: notify static lsp when label chunk available")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>
(cherry picked from commit 49ab62249ee9c0405190c0d4312f2973024a8696)

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>