ldpd: fix openbsd compilation error
pfkey.c file
> build	21-Jan-2026 15:26:35	  CC       ldpd/pfkey.o
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:26:18: error: declaration of 'union ldpd_addr' will not be visible outside of this function [-Werror,-Wvisibility]
> build	21-Jan-2026 15:26:35	                    int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                               ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:30:37: error: declaration of 'union ldpd_addr' will not be visible outside of this function [-Werror,-Wvisibility]
> build	21-Jan-2026 15:26:35	static int       pfkey_sa_add(int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                         ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:32:40: error: declaration of 'union ldpd_addr' will not be visible outside of this function [-Werror,-Wvisibility]
> build	21-Jan-2026 15:26:35	static int       pfkey_sa_remove(int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                            ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:47:19: error: declaration of 'union ldpd_addr' will not be visible outside of this function [-Werror,-Wvisibility]
> build	21-Jan-2026 15:26:35	    int af, union ldpd_addr *src, union ldpd_addr *dst, uint32_t spi,
> build	21-Jan-2026 15:26:35	                  ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:46:1: error: conflicting types for 'pfkey_send'
> build	21-Jan-2026 15:26:35	pfkey_send(int sd, uint8_t satype, uint8_t mtype, uint8_t dir,
> build	21-Jan-2026 15:26:35	^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:25:13: note: previous declaration is here
> build	21-Jan-2026 15:26:35	static int       pfkey_send(int, uint8_t, uint8_t, uint8_t,
> build	21-Jan-2026 15:26:35	                 ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:69:14: error: incompatible pointer types passing 'union ldpd_addr *' to parameter of type 'const union g_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	        addr2sa(af, src, 0, &su_src);
> build	21-Jan-2026 15:26:35	                    ^~~
> build	21-Jan-2026 15:26:35	ldpd/ldpd.h:705:42: note: passing argument to parameter 'addr' here
> build	21-Jan-2026 15:26:35	void addr2sa(int af, const union g_addr *addr, uint16_t port, union sockunion *su);
> build	21-Jan-2026 15:26:35	                                         ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:87:14: error: incompatible pointer types passing 'union ldpd_addr *' to parameter of type 'const union g_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	        addr2sa(af, dst, 0, &su_dst);
> build	21-Jan-2026 15:26:35	                    ^~~
> build	21-Jan-2026 15:26:35	ldpd/ldpd.h:705:42: note: passing argument to parameter 'addr' here
> build	21-Jan-2026 15:26:35	void addr2sa(int af, const union g_addr *addr, uint16_t port, union sockunion *su);
> build	21-Jan-2026 15:26:35	                                         ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:339:28: error: declaration of 'union ldpd_addr' will not be visible outside of this function [-Werror,-Wvisibility]
> build	21-Jan-2026 15:26:35	pfkey_sa_add(int af, union ldpd_addr *src, union ldpd_addr *dst, uint8_t keylen,
> build	21-Jan-2026 15:26:35	                           ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:339:1: error: conflicting types for 'pfkey_sa_add'
> build	21-Jan-2026 15:26:35	pfkey_sa_add(int af, union ldpd_addr *src, union ldpd_addr *dst, uint8_t keylen,
> build	21-Jan-2026 15:26:35	^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:30:13: note: previous declaration is here
> build	21-Jan-2026 15:26:35	static int       pfkey_sa_add(int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                 ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:343:10: error: incompatible pointer types passing 'union ldpd_addr *' to parameter of type 'union ldpd_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	            af, src, dst, 0, 0, 0, NULL, 0, 0, NULL, 0, 0) < 0)
> build	21-Jan-2026 15:26:35	                ^~~
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:26:29: note: passing argument to parameter here
> build	21-Jan-2026 15:26:35	                    int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                          ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:343:15: error: incompatible pointer types passing 'union ldpd_addr *' to parameter of type 'union ldpd_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	            af, src, dst, 0, 0, 0, NULL, 0, 0, NULL, 0, 0) < 0)
> build	21-Jan-2026 15:26:35	                     ^~~
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:26:48: note: passing argument to parameter here
> build	21-Jan-2026 15:26:35	                    int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                                             ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:348:10: error: incompatible pointer types passing 'union ldpd_addr *' to parameter of type 'union ldpd_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	            af, src, dst, *spi, 0, keylen, key, 0, 0, NULL, 0, 0) < 0)
> build	21-Jan-2026 15:26:35	                ^~~
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:26:29: note: passing argument to parameter here
> build	21-Jan-2026 15:26:35	                    int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                          ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:348:15: error: incompatible pointer types passing 'union ldpd_addr *' to parameter of type 'union ldpd_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	            af, src, dst, *spi, 0, keylen, key, 0, 0, NULL, 0, 0) < 0)
> build	21-Jan-2026 15:26:35	                     ^~~
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:26:48: note: passing argument to parameter here
> build	21-Jan-2026 15:26:35	                    int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                                             ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:356:31: error: declaration of 'union ldpd_addr' will not be visible outside of this function [-Werror,-Wvisibility]
> build	21-Jan-2026 15:26:35	pfkey_sa_remove(int af, union ldpd_addr *src, union ldpd_addr *dst,
> build	21-Jan-2026 15:26:35	                              ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:356:1: error: conflicting types for 'pfkey_sa_remove'
> build	21-Jan-2026 15:26:35	pfkey_sa_remove(int af, union ldpd_addr *src, union ldpd_addr *dst,
> build	21-Jan-2026 15:26:35	^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:32:13: note: previous declaration is here
> build	21-Jan-2026 15:26:35	static int       pfkey_sa_remove(int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                 ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:360:10: error: incompatible pointer types passing 'union ldpd_addr *' to parameter of type 'union ldpd_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	            af, src, dst, *spi, 0, 0, NULL, 0, 0, NULL, 0, 0) < 0)
> build	21-Jan-2026 15:26:35	                ^~~
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:26:29: note: passing argument to parameter here
> build	21-Jan-2026 15:26:35	                    int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                          ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:360:15: error: incompatible pointer types passing 'union ldpd_addr *' to parameter of type 'union ldpd_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	            af, src, dst, *spi, 0, 0, NULL, 0, 0, NULL, 0, 0) < 0)
> build	21-Jan-2026 15:26:35	                     ^~~
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:26:48: note: passing argument to parameter here
> build	21-Jan-2026 15:26:35	                    int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                                             ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:374:29: error: incompatible pointer types passing 'union g_addr *' to parameter of type 'union ldpd_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	                if (pfkey_sa_add(nbr->af, &nbr->laddr, &nbr->raddr,
> build	21-Jan-2026 15:26:35	                                          ^~~~~~~~~~~
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:30:48: note: passing argument to parameter here
> build	21-Jan-2026 15:26:35	static int       pfkey_sa_add(int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                                    ^
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:374:42: error: incompatible pointer types passing 'union g_addr *' to parameter of type 'union ldpd_addr *' [-Werror,-Wincompatible-pointer-types]
> build	21-Jan-2026 15:26:35	                if (pfkey_sa_add(nbr->af, &nbr->laddr, &nbr->raddr,
> build	21-Jan-2026 15:26:35	                                                       ^~~~~~~~~~~
> build	21-Jan-2026 15:26:35	ldpd/pfkey.c:30:67: note: passing argument to parameter here
> build	21-Jan-2026 15:26:35	static int       pfkey_sa_add(int, union ldpd_addr *, union ldpd_addr *,
> build	21-Jan-2026 15:26:35	                                                                       ^
> build	21-Jan-2026 15:26:35	fatal error: too many errors emitted, stopping now [-ferror-limit=]
> build	21-Jan-2026 15:26:35	20 errors generated.
> build	21-Jan-2026 15:26:35	gmake[1]: *** [Makefile:11031: ldpd/pfkey.o] Error 1
>

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Signed-off-by: Loïc Sang <loic.sang@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>
(cherry picked from commit e023537f6e537d6c12553fdc26406ad49598b544)

PR: 101860
Link: http://scm.6wind.com/routing/frr/log/?h=b_upstream_1125_vpws
Signed-off-by: Loïc Sang <loic.sang@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>