isisd: fix isis_circuit.c compilation
> ../sdist/isisd/isis_circuit.c: In function ‘isis_circuit_add_addr’:
> ../sdist/isisd/isis_circuit.c:397:12: error: ‘first_address’ may be used uninitialized []
>   397 |         if (first_address)
>       |            ^
> ../sdist/isisd/isis_circuit.c:314:14: note: ‘first_address’ was declared here
>  314 |         bool first_address;
>      |              ^~~~~~~~~~~~~

PR: 87185
Fixes: 28aba9c37d ("isisd: update bfd tlv variables on address change")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>