bgp_vpnv6_per_nexthop: fix prefix 172:31::30/128 not found
The following error happens:
> E           AssertionError: r2, prefix ipv6 vpn 172:31::30/128 is not installed yet
> E           assert False

The prefix 172:31::30/128 was used for a previous test, and was
removed before reaching the current test. Remove the reference
to this prefix.

Fixes: 51ae7228aeb5 ("topotests: bgp l3vpn label per nexthop, add network declaration test")
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>