bgpd: Fix compilation for Debian 11 when printing uint64 values
build	25-Mar-2026 08:53:54	  375 | #define PRIu64 "Lu"
build	25-Mar-2026 08:53:54	bgpd/bgp_flowspec_util.c: In function ‘bgp_flowspec_bitmask_decode’:
build	25-Mar-2026 08:53:54	bgpd/bgp_flowspec_util.c:476:44: error: format ‘%Lu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
build	25-Mar-2026 08:53:54	  476 |    len_written = snprintf(ptr, len_string, "%" PRIu64, value);
build	25-Mar-2026 08:53:54	      |                                            ^~~         ~~~~~
build	25-Mar-2026 08:53:54	      |                                                        |
build	25-Mar-2026 08:53:54	      |                                                        uint64_t {aka long unsigned int}
build	25-Mar-2026 08:53:54	In file included from ./lib/zebra.h:13,
build	25-Mar-2026 08:53:54	                 from bgpd/bgp_flowspec_util.c:8:
build	25-Mar-2026 08:53:54	./lib/compiler.h:375:18: note: format string is defined here

Signed-off-by: Donatas Abraitis <donatas@opensourcerouting.org>
(cherry picked from commit a44ef01d8357b9e2ea7405f3d76be5874e32a3a5)

PR: 102220
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: François Dumontet <francois.dumontet@6wind.com>