bgpd: fix nexthop group resolved over blackhole sent to zebra
The static_routing_with_ibgp_test topo2 test fails:

> 2024-03-08 13:45:11,780 ERROR: topo: test failed at "test_static_routes_topo2_ibgp/
> test_static_route_8nh_diff_AD_bgp_ecmp_p1_tc6_ibgp": Testcase test_static_route_8nh_diff_AD_bgp_ecmp_p1_tc6_ibgp : Failed
>   Error: Routes are missing in RIB

On r3, the 110.0.20.1 bgp update could not be installed.

> # show bgp ipv4
> [..]
> * i110.0.20.1/32    10.0.0.1                 0    100      0 ?
> *>i                 10.0.0.1                 0    100      0 ?
> # show ip route 110.0.21.1
> #

Actually, the BGP and ZEBRA trace indicate that an error happened:

> 2024/03/08 13:43:57 BGP: [TBQQ6-DSSPE] NHG 75757584: creation (10.0.0.1 if 0 VRF 0 wt 0   )
> 2024/03/08 13:43:57 BGP: [J3CTT-WCCCQ] parse_nexthop: 110.0.20.1/32 (peer 10.0.0.33), attaching new nexthop 75757584 (10.0.0.1 if 0 VRF 0 wt 0   )
> 2024/03/08 13:43:57 BGP: [TXA9K-GZ639] NHG 75757585: group creation (75757584)
> 2024/03/08 13:43:57 BGP: [YS6AE-ZF4N4] bgp_nhg_add_or_update_nhg_group: nhg 75757585 not sent, dependent NHG ID 75757584 not present or not installed.
> 2024/03/08 13:43:57 BGP: [J4K3G-T79S9] parse_nexthop: 110.0.20.1/32, attaching new NHG 75757585 (75757584)
> 2024/03/08 13:43:57 ZEBRA: [J611J-7TPAA] zebra_nhg_proto_add: id 75757584, blackhole nexthop not supported
> 2024/03/08 13:43:57 BGP: [V95SP-KJ8K6] Failed install of nhg 75757584

The error happens because BGP wants to create the nexthop-group 75757584,
but that nexthop is resolved over blackhole route. This is not handled
in ZEBRA, and BGP knew it but did not prevent the usage of that
nexthop-group.

> # show bgp nexthop detail
> Current BGP nexthop cache:
>  10.0.0.1 valid [IGP metric 0], #paths 8
>   blackhole
>   Last update: Fri Mar  8 13:43:57 2024
>   Paths:
>     1/1 110.0.20.1/32 VRF default flags 0x410

BGP will check if one of its nexthop resolves over a blackhole route,
and if it is the case, BGP will not use nexthop groups for the prefix
to update in ZEBRA.

Fixes: ba55599a640c ("bgpd: add nexthop group support for single path routes")

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>