bgpd: fix srv6 align the sid_func with wlib array boundaries
The topotest bgp_srv6_sid_explicit generates the crash dump:

ERROR: SEGV on unknown address 0x5110002dba30 (pc 0x55a58a813379 bp 0x7ffd2cc8ec50 sp 0x7ffd2cc8ec00 T0)
The signal is caused by a READ memory access.
    #0 0x55a58a813379 in alloc_srv6_sid_func_explicit zebra/zebra_srv6.c:1264
    #1 0x55a58a815138 in get_srv6_sid_explicit zebra/zebra_srv6.c:1611
    #2 0x55a58a8166bb in get_srv6_sid zebra/zebra_srv6.c:1807
    #3 0x55a58a8191ef in srv6_manager_get_sid_internal zebra/zebra_srv6.c:2314
    #4 0x55a58a80c0aa in hook_call_srv6_manager_get_sid zebra/zebra_srv6.c:67
    #5 0x55a58a80c671 in srv6_manager_get_sid_call zebra/zebra_srv6.c:115
    #6 0x55a58a78e956 in zread_srv6_manager_get_srv6_sid zebra/zapi_msg.c:3245
    #7 0x55a58a78f1d8 in zread_srv6_manager_request zebra/zapi_msg.c:3313
    #8 0x55a58a799321 in zserv_handle_commands zebra/zapi_msg.c:4425
    #9 0x55a58a92473c in zserv_process_messages zebra/zserv.c:521
    #10 0x781c0f978970 in event_call lib/event.c:2011
    #11 0x781c0f843d11 in frr_run lib/libfrr.c:1219
    #12 0x55a58a73079d in main zebra/main.c:550
    #13 0x781c0f22a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x781c0f22a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #15 0x55a58a6ec2b4 in _start (/usr/lib/frr/zebra+0x1d02b4)

Fixes: 4e4588fa8f ("zebra: Add functions to alloc/release SRv6 SIDs")

Signed-off-by: Dmytro Shytyi <dmytro.shytyi@6wind.com>
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>