zebra: Fix SRv6 locator delete after no prefix
A locator can be configured with a prefix:

```
segment-routing
 srv6
  locators
   locator MAIN
    prefix fcbb:bbbb:1::/48
```

Then the prefix can be removed while leaving the locator configured:

```
segment-routing
 srv6
  locators
   locator MAIN
    no prefix
```

Deleting the locator after that crashes zebra:

```
segment-routing
 srv6
  locators
   no locator MAIN
```

This triggers a NULL dereference:

```
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000048
    #0 zebra_srv6_sid_ctx_list_const_first zebra/zebra_srv6.h:232
    #1 zebra_srv6_sid_ctx_list_first zebra/zebra_srv6.h:232
    #2 no_srv6_locator zebra/zebra_srv6_vty.c:837
```

`no prefix` releases `locator->sid_block`, but
`no_srv6_locator_cmd()` walked `block->sids` before checking whether
the locator still had a SID block.

Guard the SID entry cleanup with the existing SID block check before
deleting the locator.

Signed-off-by: Carmine Scarpitta <cscarpit@cisco.com>
(cherry picked from commit 627732785732527da94e375f3a103cbe1b2bed0a)