pmd: fix compilation without pmd
Fix issue seen when running ./buildtest.sh

>   CC       pmd/pm_echo.o
> ../sdist/pmd/pm_zebra.c:46:10: fatal error: pm_tracking.h: No such file or directory
>    46 | #include "pm_tracking.h"
>       |          ^~~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [Makefile:11247: pmd/pm_zebra.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> ../sdist/pmd/pm.c:37:10: fatal error: pmd/pm_tracking.h: No such file or directory
>    37 | #include "pmd/pm_tracking.h"
>       |          ^~~~~~~~~~~~~~~~~~~
> compilation terminated.

PR: 95589
Fixes: 89085a40d8 ("pmd, *: add new path monitoring daemon")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>