bgpd: build failed due to show_adj_route_vpn() not being used
Signed-off-by: Daniel Walton <dwalton@cumulusnetworks.com>

 CC       bgp_snmp.o
  CC       bgp_ecommunity.o
  CC       bgp_mplsvpn.o
  CC       bgp_nexthop.o
bgp_mplsvpn.c:570:1: error: ‘show_adj_route_vpn’ defined but not used
[-Werror=unused-function]
 show_adj_route_vpn (struct vty *vty, struct peer *peer, struct
prefix_rd *prd, u_char use_json, afi_t afi)
 ^
  CC       bgp_damp.o
cc1: all warnings being treated as errors