bgpd: fix bgp_terminate compilation
with --disable-bgp-vnc

> bgpd/bgpd.c: In function ‘bgp_terminate’:
> bgpd/bgpd.c:9154:5: error: "ENABLE_BGP_VNC" is not defined, evaluates to 0 [-Werror=undef]
>  9154 | #if ENABLE_BGP_VNC
>       |     ^~~~~~~~~~~~~~

PR: 99844
Fixes: a7b2189257 ("bgpd: rfapi: track outstanding rib and import timers, free mem at exit")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>