builtest: fix unknown pw.h header
Error from buildtest:
- ../sdist/tests/lib/cxxcompat.c:64:10: fatal error: lib/pw.h: No such
file or directory

This file is renamed to l2vpn.h.

Fixes: 6bdac6e1b8be ("lib, yang: prepare l2vpn vpws type support")
PR: 103070
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Signed-off-by: Loïc Sang <loic.sang@6wind.com>
Acked-by: Louis Scalbert <louis.scalbert@6wind.com>