pathd: remove unused loop counters
GCC 16 doesn't like these:
```
pathd/path_pcep_debug.c:1368:21: error: variable 'i' set but not used [-Werror=unused-but-set-variable=]
```
and they are indeed just pointless.

Signed-off-by: David 'equinox' Lamparter <equinox@opensourcerouting.org>