zebra: fix compilation error on zebra_srte
The following compilation error happens:

> zebra/zebra_srte.c:355:6: error: variable 'lsp' is used uninitialized
> whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]

Fix this by initializing the lsp value.

Fixes: 2059e09996cc ("zebra: add srv6 nexthop resolution given by sr policy")
PR: 91027
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Acked-by: Louis Scalbert <louis.scalbert@6wind.com>
(cherry picked from commit 1fa99a317dfc1e553c383bcf548feae3142ed1f9)

Conflicts:
	zebra/zebra_srte.c, minor
	'zebra_lsp_t' replaced by 'struct zebra_lsp'

PR: 93645
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Louis Scalbert <louis.scalbert@6wind.com>