lib: fix a bfd compilation error with frr-format
Fix the following error when compiling with the frr-format plugin.

> In file included from lib/log.h:32,
>                  from lib/vty.h:32,
>                  from lib/command.h:26,
>                  from lib/bfd.c:25:
> lib/bfd.c: In function ‘_bfd_sess_send’:
> ./lib/zlog.h:107:20: error: format ‘%pI4’ expects argument of type ‘in_addr_t {aka unsigned int} *’, but argument 5 has type ‘struct in6_addr *’ [-Werror=format=]
>   107 |   zlog_ref(&_xref, (msg), ##__VA_ARGS__);                        \
>       |                    ^~~~~
> ./lib/zlog.h:114:26: note: in expansion of macro ‘_zlog_ecref’
>   114 | #define zlog_debug(...)  _zlog_ecref(0, LOG_DEBUG, __VA_ARGS__)
>       |                          ^~~~~~~~~~~
> lib/bfd.c:502:5: note: in expansion of macro ‘zlog_debug’
>   502 |     zlog_debug("LIB-BFD: %s %s BFD src %pI4 dst %pI4",
>       |     ^~~~~~~~~~
> ./lib/zlog.h:107:20: error: format ‘%pI4’ expects argument of type ‘in_addr_t {aka unsigned int} *’, but argument 6 has type ‘struct in6_addr *’ [-Werror=format=]
>   107 |   zlog_ref(&_xref, (msg), ##__VA_ARGS__);                        \
>       |                    ^~~~~
> ./lib/zlog.h:114:26: note: in expansion of macro ‘_zlog_ecref’
>   114 | #define zlog_debug(...)  _zlog_ecref(0, LOG_DEBUG, __VA_ARGS__)
>       |                          ^~~~~~~~~~~
> lib/bfd.c:502:5: note: in expansion of macro ‘zlog_debug’
>   502 |     zlog_debug("LIB-BFD: %s %s BFD src %pI4 dst %pI4",
>       |     ^~~~~~~~~~
> cc1: all warnings being treated as errors
> make[1]: *** [Makefile:10212: lib/bfd.lo] Error 1

PR: 85104
Fixes: 360ee2b303 ("lib: bfd, add bfd src and dst ip addresses debug logs")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: François Dumontet <francois.dumontet@6wind.com>
(cherry picked from commit 274289c5ffc64c6fa21b54b3b23e810cf570b895)

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>