zebra: wrap script support for packet length
IPtables is reveiving the packet length filtering support.

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
(cherry picked from commit 89841683a80f7909f65f1e219d6766395dc5e583)

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>

(cherry picked from commit 53cef68281ddffd13844243c5630fb273ad5b35d)

Old-PR: 62595
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Emmanuel Vize <emmanuel.vize@6wind.com>
(cherry picked from commit ad4486b8d5315691a5db35f695340d630f889e3c)

PR=76504
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Louis Scalbert <louis.scalbert@6wind.com>
(cherry picked from commit 4ea79b20805979c54c0df1260d03883a98c3be15)

Conflicts: zebra/zebra_wrap_script.c

Initialize len_written to permit compilation:

> zebra/zebra_wrap_script.c:1121:3: error: variable 'len_written' is uninitialized when used here [-Werror,-Wuninitialized]
>                 len_written += snprintf(complement_len + len_written,
>                 ^~~~~~~~~~~
> zebra/zebra_wrap_script.c:1116:17: note: initialize the variable 'len_written' to silence this warning
>         int len_written;
>                        ^
>                         = 0

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>