pmd: support name resolution for gateway tracking
it is possible to use resolution for gateway. that gateway is used as
nexthop instead of the peer itself. once the resolution done, that new
IP is submitted to nexthop tracking.

Old-PR: 65269
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Olivier Matz <olivier.matz@6wind.com>
(cherry picked from commit cb3bd6369013)

PR=76618
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Louis Scalbert <louis.scalbert@6wind.com>
(cherry picked from commit 4ae186c5e3078bc3d578beb03da669cfe14dd5f1)

Conflicts: pmd/pm.c pmd/pm_tracking.c

Adaptation to frrevent library
Use of %pSU in logs
Fix error:

> ./pmd/pm_tracking_clippy.c: In function ‘pm_tracking_gateway_ip’:
> pmd/pm_tracking.c:388:50: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
>  388 |  snprintf(ctx->gateway, sizeof(ctx->gateway), "%s", gw);
>      |                                                  ^
> pmd/pm_tracking.c:388:2: note: ‘snprintf’ output between 1 and 256 bytes into a destination of size 255
>   388 |  snprintf(ctx->gateway, sizeof(ctx->gateway), "%s", gw);
>       |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>