staticd: rename the "delete" variable to "is_delete"
The "delete" keyword is reserved one.

In file included from tests/lib/test_grpc.cpp:24:
./staticd/static_vty.h:36:14: error: expected unqualified-id before 'delete'
   36 |         bool delete;
      |              ^~~~~~
make: *** [Makefile:15562: tests/lib/test_grpc-test_grpc.o] Error 1

PR: 94545
Fixes: fc6f9d7425 ("staticd: improve CLI/northbound translation code")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Signed-off-by: Dmytro Shytyi <dmytro.shytyi@6wind.com>
Acked-by: Louis Scalbert <louis.scalbert@6wind.com>