zebra: fix zebra_cli compilation
> zebra/zebra_cli.c:847:5: error: no previous prototype for ‘ag_iter_cb’ [-Werror=missing-prototypes]
>   847 | int ag_iter_cb(const struct lyd_node *dnode, void *arg)
>       |     ^~~~~~~~~~

PR: 95710
Fixes: c9fda14399 ("zebra: make zebra build withtout mgmtd")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Loïc Sang <loic.sang@6wind.com>