lib: fix mgmt_vty_read_configs compilation
> lib/vty.c: In function ‘mgmt_vty_read_configs’:
> lib/vty.c:2293:24: error: comparison is always false due to limited range of data type [-Werror=type-limits]
>  2293 |  for (index = 0; index < array_size(mgmt_daemons); index++) {

PR: 95710
Fixes: 75e41c4e20 ("mgmtd: build without daemons dependencies")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Loïc Sang <loic.sang@6wind.com>