zebra: fix zebra_nhrp interface name check
Fix issue that was detected by the compilation error seen when running
./builtests.sh

> ../sdist/zebra/zebra_nhrp.c:621:12: error: address of array 'ifp->name' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
>         if (!ifp->name)
>             ~~~~~~^~~~

PR: 95589
Fixes: debb243b04 ("zebra: nhrp add function can be reentrant")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>