bfdd: fix compilation without bfd-tracking
Fix issue seen when running ./buildtest.sh

>   CC       bfdd/bfdd_nb_state.o
> ../sdist/bfdd/bfdd_nb_config.c:16:10: fatal error: bfd_tracking.h: No such file or directory
>    16 | #include "bfd_tracking.h"
>       |          ^~~~~~~~~~~~~~~~
> compilation terminated.

PR: 95589
Fixes: e077a7f76b ("bfdd: add plugin extension to notify filename")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>