bgpd: Ensure we correctly account for locator prefix being removed
The locator prefix is/was being tracked.  This was irrelevant
to whether or not the locator prefix was technically removed
but still present due to the way that bgpd handles path info's.

Modify the code to notice if the locator prefix is removed or
not and to do the right thing.

The test_bgp_ls_srv6_export test is failing:

FAILED test_bgp_link_state_bgp_fabric_srv6.py::test_bgp_ls_srv6_export - AssertionError: SRv6 BGP-LS NLRI/attribute mismatch on RR: Generated JSON diff error report:

  > $->routes->[V][B][I0x0][N[c65003][q4.4.4.4]]: expected has the following element at index 0 which is not present in output:

  	{
  	    "nlri": {
  	        "nlriType": "node",
  	        "protocolId": 7,
  	        "localNodeDescriptors": {
  	            "asn": 65003,
  	            "bgpRouterId": "4.4.4.4"
  	        }
  	    },
  	    "linkStateAttrs": {
  	        "srv6Capabilities": {
  	            "flags": "0x0"
  	        }
  	    }
  	}

  	Closest match in output is at index 0 with the following errors:

  	> $->routes->[V][B][I0x0][N[c65003][q4.4.4.4]][0]->linkStateAttrs: expected has key 'srv6Capabilities' which is not present in output

assert Generated JSON diff error report:

  > $->routes->[V][B][I0x0][N[c65003][q4.4.4.4]]: expected has the following element at index 0 which is not present in output:

  	{
  	    "nlri": {
  	        "nlriType": "node",
  	        "protocolId": 7,
  	        "localNodeDescriptors": {
  	            "asn": 65003,
  	            "bgpRouterId": "4.4.4.4"
  	        }
  	    },
  	    "linkStateAttrs": {
  	        "srv6Capabilities": {
  	            "flags": "0x0"
  	        }
  	    }
  	}

  	Closest match in output is at index 0 with the following errors:

  	> $->routes->[V][B][I0x0][N[c65003][q4.4.4.4]][0]->linkStateAttrs: expected has key 'srv6Capabilities' which is not present in output

Without these changes.

Signed-off-by: Donald Sharp <sharpd@nvidia.com>