pmd: add a `count` parameter
In order to use IPSLA tracking, pings have to be sent not one by one
(which is what the ICMP tracker do for now) but `count` by `count`. This
will allow calculating stats not only for the whole pm session but also
for each bulk of `count` pings.
Consequently, the accepted parameters of the commands configuring a pm
session are now conditioned to its type: `count` can be set only on an
icmp_sla session whereas `timeout` and the different `retries`
parameters (`mode`, `up_count`, `down_count`, `threshold` and `total`)
can be set only in an icmp_echo session.

PR: 86715
Signed-off-by: Romain Trojani-Bigot <romain.trojani_bigot@6wind.com>
Acked-by: Romain Delhomel <romain.delhomel@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>
(cherry picked from commit 2ed77f63bb0fc3bf387a2465a2f681b24c4b41b0)

Conflicts: pmd/pm_echo.c

Adapt to frrevent library
Use %pSU
Merge e263011539 ("pmd: fix ICMP6")
Fix false positive compilation warning:

> pmd/pm_echo.c: In function ‘pm_echo_send’:
> pmd/pm_echo.c:868:13: error: ‘iph’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>   868 |     iph->id = random();
>       |     ~~~~~~~~^~~~~~~~~~

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>