pathd: handle bgp te entries at srte_policy level
For each change in BGP TE entries, update the srte policy
concerned, and the derived candidate paths entries.

For each change in policy-template, and each change in the
candidate template, update the changes for each concerned
bgp TE entries.

A new TEMPLATE flag is added for each srte policy and each
candidate path derived from the policy-template. This is to
prevent from a configured srte policy to being removed.
Similarly, a CONFIG flag is used on srte policy to indicate
 the policy is used by the yang configuration. This is to
prevent from removing the srte policy entry when no bgp te
entry is needed.

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Francois Dumontet <francois.dumontet@6wind.com>

fix LLVM compilation error

../sdist/pathd/path_triggered.c: In function ‘srte_triggered_update_entry’:
../sdist/pathd/path_triggered.c:93:60: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
   snprintf(policy->name, sizeof(policy->name),  "____0__",
                                                            ^
../sdist/pathd/path_triggered.c:93:3: note: ‘snprintf’ output between 8 and 65 bytes into a destination of size 64
   snprintf(policy->name, sizeof(policy->name),  "____0__",
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     policy_template->name, policy_template->counter);

PR=80628
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Francois Dumontet <francois.dumontet@6wind.com>
(cherry picked from commit cd9d9331dede4c3bbf248fed69d8d781c50e56b9)

Conflicts:
    pathd/path_nb_config.c
    pathd/path_template.c
    pathd/pathd.c
    pathd/pathd.h

Adaptations to ab7fe289b9 ("pathd: Handle PCInitiated configuration,
main thread. (3/4)")

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>