pmd: peer can be an hostname
it is possible to configure a servername as string, instead of IPv4 or
IPv6 address. this commit just permits the vty configuration. however,
as the resolution is not put in place, the session will not start if
that string is not an ipv4 or ipv6 address. the change consists in
changing the index of the pm session, changing the vty, and changing the
order of the checks when looking for the session. for instance, the
nexthop tracking is done only after having resolved the peer address.
The commit also adds a define in command.h that is retrieved from a
backport.

Old-PR: 65269
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Olivier Matz <olivier.matz@6wind.com>
(cherry picked from commit d93ef216ee95)

PR=76618
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Louis Scalbert <louis.scalbert@6wind.com>
(cherry picked from commit ddf1063b14c23d347e23fa89fd81577b21652524)

Conflicts: pmd/pm.c pmd/pm.h pmd/pm_vty.c

Fix some minor compilation issues (unused variables and variable
declarations were in next commits)
Fix issue:

> pmd/pm.c: In function ‘pm_lookup_session’:
> pmd/pm.c:232:48: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
>   232 |  snprintf(pm.key.peer, sizeof(pm.key.peer), "%s", peer);
>       |                                                ^
> pmd/pm.c:232:2: note: ‘snprintf’ output between 1 and 256 bytes into a destination of size 255
>   232 |  snprintf(pm.key.peer, sizeof(pm.key.peer), "%s", peer);
>       |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           pmd/pm_zebra.c

Use of %pSU in logs
Adapt pm_echo_get_alarm_str()

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>