tests: fix zebra mpls unit tests
The mpls unit tests fail.
Some undefined variables and functions are missing:

> /usr/bin/ld: zebra/label_manager.o: warning: relocation against `label_manager_platform_max_input' in read-only section `.text'
> /usr/bin/ld: zebra/label_manager.o: in function `label_manager_init':
> /root/frr/zebra/label_manager.c:295: undefined reference to `label_manager_platform_max_input'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:295: undefined reference to `label_manager_platform_max_input'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:317: undefined reference to `label_manager_platform_value'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:317: undefined reference to `label_manager_platform_value'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:319: undefined reference to `label_manager_platform_value'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:319: undefined reference to `label_manager_platform_value'
> /usr/bin/ld: zebra/label_manager.o: in function `release_label_chunk':
> /root/frr/zebra/label_manager.c:621: undefined reference to `zebra_mpls_is_platform_auto_enabled'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:628: undefined reference to `label_manager_platform_max_input'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:628: undefined reference to `label_manager_platform_max_input'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:629: undefined reference to `label_manager_platform_max_input'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:630: undefined reference to `zebra_mpls_platform_labels_update'
> /usr/bin/ld: zebra/label_manager.o: in function `label_manager_get_chunk':
> /root/frr/zebra/label_manager.c:665: undefined reference to `zebra_mpls_is_platform_auto_enabled'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:671: undefined reference to `label_manager_platform_max_input'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:671: undefined reference to `label_manager_platform_max_input'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:672: undefined reference to `label_manager_platform_max_input'
> /usr/bin/ld: /root/frr/zebra/label_manager.c:673: undefined reference to `zebra_mpls_platform_labels_update'

Fix this by duplicating it in the test file.

Fixes: e68369da519e ("zebra: restore platform_labels at platform auto")

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>