pathd: fix compilation error on flex-algo
The following error message happens:

> pathd/path_flex_algo.c:461:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

Fix this by adding a break in the last switch before default.

Fixes: adcf256e1514 ("pathd,doc: flex-algo candidate paths")

PR: 91027
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Louis Scalbert <louis.scalbert@6wind.com>
(cherry picked from commit 5e705d91e31ebc8e1de58ed0c6694db13e789e1f)

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>