pathd: add policy-template node
This node when configured, will be used to apply
a candidate policy entry for an incoming BGP next
hop.
Add code in charge of handling policy template contexts.

fix LLVM compilation error
../sdist/pathd/path_triggered.c: In function ‘srte_triggered_update_entry’:
../sdist/pathd/path_triggered.c:93:60: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
   snprintf(policy->name, sizeof(policy->name),  "____0__",
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     policy_template->name, policy_template->counter);

PR=80628
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
Acked-by: Francois Dumontet <francois.dumontet@6wind.com>
(cherry picked from commit ca30bc6d7d6db734d4618d7c03a2dd814f173ac5)

Conflicts: pathd/pathd.c vtysh/vtysh.c

Remove --enable-srte

Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>