ospfd: fix compilation with snmp
> ospfd/ospf_snmp.c: In function ‘ospfAreaRangeLookup’:
> ospfd/ospf_snmp.c:1096:48: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
>  1096 |   if (v->namelen + IN_ADDR_SIZE + IN_ADDR_SIZE != *length)
>       |                                                ^~
> ospfd/ospf_snmp.c: In function ‘ospfHostLookup’:
> ospfd/ospf_snmp.c:1234:15: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
>  1234 |   if (*length != v->namelen + IN_ADDR_SIZE + 1)
>       |               ^~
> ospfd/ospf_snmp.c: In function ‘ospfIfLookup’:
> ospfd/ospf_snmp.c:1531:15: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
>  1531 |   if (*length != v->namelen + IN_ADDR_SIZE + 1)
>       |               ^~
> ospfd/ospf_snmp.c: In function ‘ospfIfMetricLookup’:
> ospfd/ospf_snmp.c:1671:15: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
>  1671 |   if (*length != v->namelen + IN_ADDR_SIZE + 1 + 1)
>       |               ^~
> ospfd/ospf_snmp.c: In function ‘ospfVirtIfLookup’:
> ospfd/ospf_snmp.c:1867:15: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
>  1867 |   if (*length != v->namelen + IN_ADDR_SIZE + IN_ADDR_SIZE)
>       |               ^~
> ospfd/ospf_snmp.c: In function ‘ospfNbrLookup’:
> ospfd/ospf_snmp.c:2044:15: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
>  2044 |   if (*length != v->namelen + IN_ADDR_SIZE + 1)
>       |               ^~
> ospfd/ospf_snmp.c: In function ‘ospfExtLsdbLookup’:
> ospfd/ospf_snmp.c:2230:15: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
>  2230 |   if (*length != v->namelen + 1 + IN_ADDR_SIZE + IN_ADDR_SIZE)
>       |               ^~
> cc1: all warnings being treated as errors

Fixes: 7f1b2a509e ("lib: Change sizeof(..) to actual byte sizes for addresses")
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>